##################################################################################
###################################################### Nasal Septum asymmetry 2022

### Packages and functions
library(Arothron)
library(Morpho)
library(geomorph)
library(rgl)

source("Functions.R")


############################################################ READ AND PREPARE DATA

# Read landmark replicas (41 landmarks, set_1 and set_2), create a set to use for 
# computing the nasal septum deviation (set_dev).
set_1<-read.amira.dir("landmark_rep1",41)
set_2<-read.amira.dir("landmark_rep2",41)

set_dev<-set_1


# Remove the landmarks used for septum deviation from set_1 and set_2. Those landmarks
# are only necessary for the computation of the nasal septum deviation but will not be
# included in the statistical analysis.
set_1<-set_1[-c(1,2,3,23,24,41),,]
set_2<-set_2[-c(1,2,3,23,24,41),,]


# Read specimen information table and use it to create Sex and Age variables
info<-read.csv("info_specimens.csv")

sex<-as.factor(info$GENDER)
age<-info$AGENUM


###################################################################### PRELIMINARY

# Align specimens' landmark configurations in set_dev using Generalised Procrustes
# Analysis (GPA), taking care of excluding the landmark recording the maximum lateral
# deviation of the septum (here the landmark 41, the last in the configuration). GPA
# is performed using the function 'procSym' from the 'Morpho' package. On the aligned
# specimens, compute nasal septum deviation (dd) using the bespoke function 'dist2plane',
# cycling it to each specimen using a for loop.
aa<-procSym(set_dev,use.lm=1:40)

dd<-rep(NA,dim(set_dev)[3])
for(i in 1:dim(set_dev)[3]){
  dd[i]<-dist2plane(aa$rotated[1:10,,i],aa$rotated[41,,i],absolute=F)
}


# Preliminary analysis to investigate the effect of sex on nasal septum deviation.
# Transparent colours are generated for females (colf) and males (colm); density
# distributions are computed for each sex (df and dm) and then plotted; finally,
# Kolmogorov-Smirnov test is performed to check for significant differences
# in relative and absolute deviation (magnitude) between the sexes.
colf<-col2rgb("orange",F)/255
  colf<-rgb(colf[1],colf[2],colf[3],0.5)
colm<-col2rgb("dodgerblue2",F)/255
  colm<-rgb(colm[1],colm[2],colm[3],0.5)

df<-density(dd[sex=="FEMALE"])
dm<-density(dd[sex=="MALE"])

plot(NA,xlim=c(-0.03,0.04),ylim=c(0,140),xlab="Septal Deviation (signed)",ylab="Density")
  polygon(dm$x,dm$y,col=colm,border=NA)
  polygon(df$x,df$y,col=colf,border=NA)
    abline(v=0,lty="dashed")
legend("topright",legend=c("Female","Male"),pt.bg=c(colf,colm),pch=22)

ks.test(dd~sex)
ks.test(abs(dd)~sex)


# Preliminary analysis to investigate the effect of side and age on nasal septum
# deviation. Side is assigned right (rx) if dd>0, left (lx) otherwise. Specific
# colours are assigned to each side (colside). A scatterplot is produced, showing
# the relationship between magnitude of deviation (absolute deviation) and age.
# Each side is highlighted using a convex hull generated by the bespoke function
# 'groupHull'. Finally, a linear model is fitted to the data to test the effect
# of age on septal deviation based on side.
side<-ifelse(dd>0,"rx","lx")
  side<-as.factor(side)
colside<-ifelse(side=="rx","darkgreen","blue")

plot(age,abs(dd),cex=0,xlab="Age",ylab="Septal Deviation (absolute - magnitude)")
  groupHull(age,abs(dd),group=side,cols=c("blue","darkgreen"),border=NA)
  points(age,abs(dd),bg=colside,pch=21,cex=1.5)
legend("topleft",legend=c("LX","RX"),pt.bg=c("darkgreen","blue"),pch=21)

summary(lm(abs(dd)~age+side))


####################################################### TEST ASYMMETRY: APPROACH 1

# Test for morphological differences between replicas using ANalysis Of VAriance
# (ANOVA). First, the two replicas are combined in a single array (r12) using the
# function 'bindArr' from the package 'Morpho'; then, factors for replica (rep)
# and individual (ind) are generated to be used in the ANOVA model. The whole
# combined set is aligned using GPA, this time using the function 'gpagen' from
# the package 'geomorph' for compatibility with the Procrustes ANOVA function
# ('procD.lm') used for testing.
r12<-bindArr(set_1,set_2,along=3)
  
rep<-sort(rep(1:2,10))
ind<-rep(1:10,2)

p12<-gpagen(r12)
  dimnames(p12$coords)[[3]]<-NULL

gdf<-geomorph.data.frame(coords=p12$coords,rep=rep,ind=ind)
aov1<-procD.lm(coords~rep*ind,data=gdf,SS.type="I")
  summary(aov1)


# Mirroring landmark data (both replicas). The mirroring is performed using the
# function 'mirror', from the package 'Morpho', applied to each specimen in a for
# loop. Once mirrored, the landmarks of the mirrored sets need relabelling, so
# that homology between the original and mirrored specimens is ensured. The step
# of relabelling takes place by switching positions of the left and right landmarks
# (newpos) in the array, while keeping the landmarks on the Medial plane in the
# same position.
set_mir<-set_1*NA
for(i in 1:dim(set_mir)[3]){
  set_mir[,,i]<-mirror(set_1[,,i],pcAlign=T)
}

Medial<-1:7
Left<-seq(8,34,2)
Right<-seq(9,35,2)
newpos<-cbind(Right,Left)
newpos<-c(t(newpos))

set_mir<-set_mir[c(Medial,newpos),,]


# Combine set_1 and its mirrored version (set_mir) using the function 'bindArr'
# from the package 'Morpho'. The combined dataset (shapeall) undergoes GPA for
# aligning all specimens together, original and mirrored ones.
shapeall<-bindArr(set_1,set_mir,along=3)
gpa<-procSym(shapeall)


# Compute the amount of morphological variance explained by asymmetry, and
# compute the contribution of Fluctuating and Directional asymmetry to that
# variance.
compAsym<-splitAsym(gpa$PCscores,1:10,11:20)

comp<-lapply(compAsym,round,digits=4)
lapply(comp,function(x) round(x*100,2))


# Perform ANOVA to test for asymmetry, deviation and their combined effect on
# the morphology. We generate factors to represent side (mirr), sex, individuals
# (ind) and age, to control for their effect in the model. The nasal septum
# deviation is transformed too, so that it is associated to both the original
# and the mirrored datasets (dev). We extract the values PC scores previously
# computed via GPA on the combined dataset shapeall. For compatibility with the
# Procrustes ANOVA function ('procD.lm'), we build a dataframe including all
# necessary elements to use in the model, through the function 'geomorph.data.frame',
# from the package 'geomorph'. Finally, we compute the model, including independent
# variables and interactions relevant to the test of asymmetry (see main text of
# the paper for details).
mirr<-c(rep("ori",10),rep("mirr",10))
sex<-rep(sex,2)
ind<-rep(1:10,2)
age<-rep(age,2)

dev<-rep(dd,2)

pcscores<-gpa$PCscores
  rownames(pcscores)<-NULL

gdf<-geomorph.data.frame(coords=pcscores,ind=ind,sex=sex,mirr=mirr,dev=dev,age=age)

mod<-procD.lm(coords~mirr+ind:mirr+dev+age+dev:mirr+sex,data=gdf,SS.type="III")
summary(mod)


####################################################### TEST ASYMMETRY: APPROACH 2

# Compute symmetric and asymmetric components from the GPA aligned coordinates of
# the combined dataset shapeall (original + mirrored). The components so computed,
# represent the difference between original and mirrored specimens, thus removing
# the need of testing for the side in the modelling phase (see below).
gpa<-procSym(shapeall)

symsh<-(gpa$rot[,,1:10]+gpa$rot[,,11:20])/2
asymsh<-gpa$rot[,,1:10]-gpa$rot[,,11:20]


# Perform Principal Component Analysis (PCA) on the symmetric component (pcaSym),
# compute the percentage of Variance explained by the PC axes, and plot the first
# and second axes of variation (PC1 and PC2). The function 'shade3d' from the 'rgl'
# package can then be used to show the shape variations computed on the mesh.
pcaSym<-prcomp(vecx(symsh),scale.=F,center=T,retx=T)

percVar<-round((pcaSym$sdev^2)/sum(pcaSym$sdev^2)*100,2)
  xlab<-paste("PC1 - Symmetric - ",paste(percVar[1],"%",sep=""),sep="")
  ylab<-paste("PC2 - Symmetric - ",paste(percVar[2],"%",sep=""),sep="")

plot(NA,pch=21,cex=0,xlim=c(-0.09,0.09),ylim=c(-0.08,0.08),xlab=xlab,ylab=ylab)
  abline(h=0,v=0,lty="dashed",col="darkgrey")
  groupHull(pcaSym$x[,1],pcaSym$x[,2],side,cols=c("blue","darkgreen"),alpha=0.2,border=NA)
  points(pcaSym$x[,c(1,2)],pch=21,cex=1.5,bg=colside)
legend("bottomleft",legend=c("LX","RX"),pt.bg=c("darkgreen","blue"),pch=21)


# Compute and show the shape variations of the symmetric component. (In a previous
# moment, we have calculated the specimen that is morphologically closest to the
# mean shape of the sample, which is the one used to show the shape variations).
# The mesh is warped on the mean shape via Thin-Plate Spline (TPS, 'tps3d' from
# package 'Morpho') and then the PC extremes are found using the function, from
# 'Morpho', 'restoreShapes'. the mean mesh is then warped along these extremes
# via TPS.
meanSym<-apply(symsh,1:2,mean)

cloMesh<-file2mesh("shape_variations/mesh_tps.ply")
cloLand<-read.amira.set("shape_variations/mesh_tps_Landmarks.txt",41)
  cloLand<-drop(cloLand[-c(1,2,3,23,24,41),,])
  
meanMesh<-tps3d(cloMesh,cloLand,meanSym)

pc1<-restoreShapes(pcaSym$x[,1],pcaSym$rotation[,1],meanSym)
  pc1min<-pc1[,,which.min(pcaSym$x[,1])]
  pc1max<-pc1[,,which.max(pcaSym$x[,1])]
pc2<-restoreShapes(pcaSym$x[,2],pcaSym$rotation[,2],meanSym)
  pc2min<-pc2[,,which.min(pcaSym$x[,2])]
  pc2max<-pc2[,,which.max(pcaSym$x[,2])]

min1<-tps3d(meanMesh,meanSym,pc1min)
max1<-tps3d(meanMesh,meanSym,pc1max)
min2<-tps3d(meanMesh,meanSym,pc2min)
max2<-tps3d(meanMesh,meanSym,pc2max)

shade3d(min1,col="grey",alpha=0.5)
shade3d(max1,col="red",alpha=0.3)

shade3d(min2,col="grey",alpha=0.5)
shade3d(max2,col="red",alpha=0.3)


# Compute PCA for the asymmetric component, similarly to what already done
# for the symmetric component.
pcaAsym<-prcomp(vecx(asymsh),scale.=F,center=,retx=T)

percVar<-round((pcaAsym$sdev^2)/sum(pcaAsym$sdev^2)*100,2)
  xlab<-paste("PC1 - Asymmetric - ",paste(percVar[1],"%",sep=""),sep="")
  ylab<-paste("PC2 - Asymmetric - ",paste(percVar[2],"%",sep=""),sep="")

plot(NA,pch=21,cex=0,xlim=c(-0.04,0.07),ylim=c(-0.06,0.05),xlab=xlab,ylab=ylab)
  abline(h=0,v=0,lty="dashed",col="darkgrey")
  for(i in 1:nrow(pcaAsym$x)){
    arrows(0,0,pcaAsym$x[i,1],pcaAsym$x[i,2],length=0,col="grey60",)
  }
  points(pcaAsym$x[,c(1,2)],pch=21,cex=abs(dd)*150,bg=colside)


# Compute shape variations for the asymmetric component, similarly to wwhat
# previously done for the symmetric component.
rotAsym<-revertPCA(pcaAsym$x,pcaAsym$rotation)
rotAsym<-vecx(rotAsym,revert=T,lmdim=3)
meanAsym<-apply(rotAsym,1:2,mean)
  
a.pc1<-restoreShapes(pcaAsym$x[,1],pcaAsym$rotation[,1],meanAsym)
  a.pc1min<-a.pc1[,,which.min(pcaAsym$x[,1])]
  a.pc1max<-a.pc1[,,which.max(pcaAsym$x[,1])]
a.pc2<-restoreShapes(pcaAsym$x[,2],pcaAsym$rotation[,2],meanAsym)
  a.pc2min<-a.pc2[,,which.min(pcaAsym$x[,2])]
  a.pc2max<-a.pc2[,,which.max(pcaAsym$x[,2])]

a.pc1min<-meanSym+a.pc1min
a.pc1max<-meanSym+a.pc1max
a.pc2min<-meanSym+a.pc2min
a.pc2max<-meanSym+a.pc2max

a.min1<-tps3d(meanMesh,meanSym,a.pc1min*10) # enhanced 10 times
a.max1<-tps3d(meanMesh,meanSym,a.pc1max*10) # enhanced 10 times
a.min2<-tps3d(meanMesh,meanSym,a.pc2min*10) # enhanced 10 times
a.max2<-tps3d(meanMesh,meanSym,a.pc2max*10) # enhanced 10 times

shade3d(a.min1,col="grey",alpha=0.5)
shade3d(a.max1,col="red",alpha=0.3)

shade3d(a.min2,col="grey",alpha=0.5)
shade3d(a.max2,col="red",alpha=0.3)

mfrow3d(1,2,sharedMouse=T)
shade3d(a.min1,col="grey",alpha=1) ; next3d()
shade3d(a.max1,col="grey",alpha=1)

mfrow3d(1,2,sharedMouse=T)
shade3d(a.min2,col="grey",alpha=1) ; next3d()
shade3d(a.max2,col="grey",alpha=1)


#  Perform ANOVAs to test for the effect of nasal septum deviation on the symmetric
# and asymmetric components, while controlling for the effects of sex and age.
gdfSym<-geomorph.data.frame(coords=pcaSym$x,sex=sex[1:10],age=age[1:10],dev=dd)
modSym<-procD.lm(coords~dev+age+sex,data=gdfSym,SS.type="III")
summary(modSym)

gdfAsym<-geomorph.data.frame(coords=pcaAsym$x,sex=sex[1:10],age=age[1:10],dev=dd)
modAsym<-procD.lm(coords~dev+age+sex,data=gdfAsym,SS.type="III")
summary(modAsym)


#################################################################### END OF SCRIPT
##################################################################################


